### ISSUE TITLE
Does not run on Linux

### ISSUE THREAD

**Issue by vincepmartin** [Andykmcc/project-graph#22]
Installing on Linux mint is causing some problems. 

**On npm install I get the following warnings**

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

**Running the application with npm run start:dev gives the following outout:**

robotburrito@robotburrito ~/Code/project-graph $ npm run start:dev

> project-graph@0.1.0 start:dev /home/robotburrito/Code/project-graph
> node-inspector --web-port=9090 & nodemon --debug ./bin/www

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug ./bin/www`
Node Inspector v0.12.8
Visit http://127.0.0.1:9090/?port=5858 to start debugging.
Debugger listening on [::]:5858
module.js:442
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/robotburrito/Code/project-graph/node_modules/neo4j-driver/lib/v1/result.js:33:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
[nodemon] app crashed - waiting for file changes before starting...

**Will attempt to install babel-polyfill**
robotburrito@robotburrito ~/Code/project-graph $ npm install babel-polyfill
project-graph@0.1.0 /home/robotburrito/Code/project-graph
└─┬ babel-polyfill@6.16.0 
  ├── babel-runtime@6.18.0 
  ├── core-js@2.4.1 
  └── regenerator-runtime@0.9.6 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

******** Attempt to run again.
robotburrito@robotburrito ~/Code/project-graph $ npm run start:dev

> project-graph@0.1.0 start:dev /home/robotburrito/Code/project-graph
> node-inspector --web-port=9090 & nodemon --debug ./bin/www

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node --debug ./bin/www`
Node Inspector v0.12.8
Visit http://127.0.0.1:9090/?port=5858 to start debugging.
Debugger listening on [::]:5858
/home/robotburrito/Code/project-graph/node_modules/neo4j-driver/lib/v1/internal/connector.js:105
  var scheme = url.match(URLREGEX)[1] || '';
                  ^

TypeError: Cannot read property 'match' of undefined
    at parseScheme (/home/robotburrito/Code/project-graph/node_modules/neo4j-driver/lib/v1/internal/connector.js:105:19)
    at Object.driver (/home/robotburrito/Code/project-graph/node_modules/neo4j-driver/lib/v1/index.js:143:43)
    at Object.<anonymous> (/home/robotburrito/Code/project-graph/src/db/index.js:8:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Andykmcc** [comment]
i think this was the result of not having a file with DB info. i've updated master so you shouldnt get this error.

**Comment by vincepmartin** [comment]
Who cares. Might be fixed... I'm not running linux anymore.

**Comment by Andykmcc** [comment]
good enough for me
